# Generated by Django 5.1.7 on 2025-03-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('ingredients', models.TextField()),
                ('nutrition_info', models.TextField()),
            ],
        ),
    ]
